name: Release NixOS Branding npm package
run-name: ${{ github.actor }} is releasing a new version of the branding npm package

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build-npm-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Build npm package
        run: |
          nix build .\#nixos-branding.npm-package \
            --print-build-logs \
            --out-link result-npm-package
          mkdir --parents ./build
          cp --recursive --dereference ./result-npm-package/* ./build
      - name: Publish npm package
        run: npm publish
        working-directory: ./build
